version: 2
jobs:
  output-partners:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo curl -fLSs https://circle.ci/cli | sudo bash
      - run: |
          mkdir -p data/partner-orbs
          printf "$ORB_PARTNERS" > data/partner-orbs/partners.txt

      - run: node query-partner-orbs-prod.js

      - store_artifacts:
          path: data/partner-orbs

workflows:
  version: 2
  query-partners:
    jobs:
      - output-partners:
          context: orbs
