version: 2
jobs:
  output-partners:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: |
          mkdir project/data/partner-orbs
          echo "$ORB_PARTNERS" > project/data/partner-orbs/partners.txt

      - run: node query-partner-orbs-prod.js

      - store_artifacts:
          path: data/partner-orbs/parter-orbs.csv

workflows:
  version: 2
  query-partners:
    jobs:
      - output-partners:
          context: orbs